---
title: "Data Science Project"
author: "Gaocha Lee, Elizabeth Cain, Maya Fernandez, and Stephanie Konadu-Acheampong "
date: "3/5/2021"
output: 
  html_document:
    keep_md: TRUE
    toc: TRUE
    toc_float: TRUE
    df_print: paged
    code_download: true
    code_folding: hide
---


```{r setup, include=FALSE}
# knitr::opts_chunk$set(echo = TRUE, message = TRUE, warning = TRUE)
```


```{r libraries}
library(readr)
library(tidyverse)
library(lubridate)
library(maps)          
library(ggmap)
library(RColorBrewer)  # for color palettes
library(sf)            # for working with spatial data
library(leaflet)       # for highly customizable mapping
library(ggthemes)      # for more themes (including theme_map())
library(plotly)        # for the ggplotly() - basic interactivity
library(gganimate)     # for adding animation layers to ggplots
library(transformr)
library(ggimage)
theme_set(theme_minimal())
```

```{r}

dataset <- read_csv("Data.csv") %>% 
  mutate(AgeCat = cut(Age, breaks = c(0,13,18,23,33,45,60), labels = c("0-13", "13-18", "18-23", "23-33", "33-45", "45-60"))) %>%
  mutate(avgsleep = mean(Sleep)) %>% 
  mutate(SocialCat = cut_number(SocialMedia, n = 3))
  
#labels = "0-1", "1-3", "3-10" label social media 

View(dataset)

```

```{r}
#demographics
dataset %>% 
  ggplot(aes(x = Age)) +
  geom_bar(fill = "steelblue1") +
  labs(title = "Number of Survey Respondents by Age", x = "Age", y = "")

```

```{r}
#demographics
dataset %>% 
  ggplot(aes(x = Region)) +
  geom_bar(fill = "steelblue1") +
  labs(title = "Number of Survey Respondents by Region", x = "", y = "")
```

```{r}

#not from test file
dataset %>% 
  group_by(Age) %>% 
  
  ggplot(aes(x = Age, y = avgsleep)) +
  geom_col() +
  # facet_wrap(vars(Age)) +
  labs(title = "Connection With Loved Ones", 
       subtitle = "Students Who Find Themselves More Connected with Family, Close Friends, and Relatives")

```

```{r}

#was in test file 

dataset %>%
  group_by(Age, Connection) %>%
  summarise(avgclasstime = mean(OnlineClass)) %>%
  ggplot(aes(x = Age,
             y = avgclasstime, 
             color = Connection)) +
  geom_jitter() +
  # facet_wrap(vars(Connection))+
  labs(x = "Age", 
       y = "", 
       title = "Average Amount of Hours Spent in Class by Age")




```


```{r}
#in project file 
#preferred graph 

dataset %>%
  group_by(AgeCat, Connection, Region) %>% 
  ggplot(aes(x = AgeCat,
             y = OnlineClass)) +
  geom_boxplot() +
  labs(x = "Age", 
       y = "", 
       title = "Comparing Hours Spent in Class Per Day by Age") +
  theme(axis.line = element_blank(), 
        panel.grid = element_blank(), 
        plot.title.position= "plot", 
        strip.text.x = element_blank())

newdataset 

```


```{r}
#not in project file

dataset %>%
  # mutate(str_sub())
  group_by(AgeCat, Connection, Region) %>%
  # summarise(avgclasstime = mean(OnlineClass)) %>%
  ggplot(aes(x = AgeCat,
             y = OnlineClass, 
             fill = Connection)) +
  geom_boxplot() +
  facet_wrap(vars(Region))+
  labs(x = "Age", 
       y = "", 
       title = "Average Amount of Hours Spent in Class by Age")
newdataset 

```

```{r}
dataset %>% 
  ggplot(aes(x = SocialCat, 
             y = Sleep, 
             color = AgeCat)) +
  geom_boxplot() +
  # facet_wrap(vars(AgeCat)) +
  labs(y = "", 
       x = "", 
       title = "Average Amount of Sleep and Media Use in Hours by Age Category") +
  theme(axis.line = element_blank(), 
        panel.grid = element_blank(), 
        plot.title.position= "plot", 
        legend.position = "none")+
  scale_color_viridis_d()
  
```


```{r}
#scatterplot 

dataset %>% 
  group_by(SocialMedia, avgsleep, AgeCat, Sleep) %>%
  summarise(avgmedia = mean(SocialMedia)) %>%
  ggplot(aes(x = avgmedia, 
             y = avgsleep, 
             color = AgeCat)) +
  geom_jitter() +
  facet_wrap(vars(AgeCat)) +
  labs(y = "", 
       x = "Average Hours of Media Use", 
       title = "Average Amount of Sleep and Media Use in Hours by Age Category") +
  theme(axis.line = element_blank(), 
        panel.grid = element_blank(), 
        plot.title.position= "plot", 
        legend.position = "none")+
  scale_color_viridis_d()
```


